# Write your MySQL query statement below
SELECT QUERY_NAME,ROUND(SUM(RATING/POSITION)/COUNT(RATING),2) AS QUALITY,ROUND(SUM(case when rating<3 then 1 else 0 end)*100/COUNT(*),2) AS POOR_QUERY_PERCENTAGE 
FROM QUERIES
GROUP BY QUERY_NAME;